version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_PASSWORD: teste@123
    volumes:
      - ~/db_prontu:/var/lib/postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  my-db: